### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by duanzhibin** [mingyuanzhou/GBN#1]
错误使用 mex
   正在创建库 CRT_sum_mex_matrix_v1.lib 和对象 CRT_sum_mex_matrix_v1.exp
CRT_sum_mex_matrix_v1.obj : error LNK2019: 无法解析的外部符号 random，该符号在函数 mexFunction 中被引用
CRT_sum_mex_matrix_v1.mexw64 : fatal error LNK1120: 1 个无法解析的外部命令

出错 make (line 3)
mex -largeArrayDims CRT_sum_mex_matrix_v1.c;

**Comment by mingyuanzhou** [comment]
maybe this is due to the mex compiler issue with your computer. Maybe you can try using Mac or Linux.
