### ISSUE TITLE
where are the local files?

### ISSUE THREAD

**Issue by bhomass** [mingyuanzhou/GBN#2]
The sample code refers to data files on your personal computer, like 

load(['/Users/zhoum/Box Sync/GBN_results/results1_global/ZGlobalTrim_20newsBydate_K0_',num2str(K),'_T_5_eta0',num2str(eta0*1000),'_PreTrain0_AllForPhi0_TrimStrategy5_Trial1_Data.mat'])

How can we reproduce the results? Can you make them available?

**Comment by mingyuanzhou** [comment]
example mat files can be found at [plot_topics_tree](https://github.com/mingyuanzhou/GBN/tree/master/plot_topics_tree)
and
https://github.com/mingyuanzhou/GBN/tree/master/plot_images_tree
